import React from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';

const Lodging = () => {
    return (
        <div>
            <Header/>
           <h1>ils sont beaux nos logements vous aimez celui-ci ???</h1> 
           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati similique non nisi! Sapiente eum, odio, officia ab voluptates culpa aperiam est quasi minima velit, blanditiis voluptas! Adipisci eligendi vero ad dolore, animi consectetur eius sit voluptatibus quas pariatur omnis soluta, magnam itaque nesciunt laudantium non excepturi aliquid tempore aliquam officiis similique. Ipsam praesentium reprehenderit ut temporibus eaque sapiente voluptatibus architecto? Dignissimos praesentium totam quisquam illum fuga deleniti commodi, perferendis ipsam consequuntur. Molestiae necessitatibus voluptate magnam sapiente quia optio consectetur esse expedita est sunt qui distinctio nihil ducimus commodi iure ab deserunt alias cupiditate, ipsam ullam numquam saepe assumenda facilis impedit? Nam deserunt officia magni a hic facilis tempora! At ab sequi sint corporis voluptatem distinctio, nobis provident cupiditate soluta tempora nesciunt enim voluptates sapiente quia dicta deleniti nemo quaerat doloremque adipisci, ipsum quasi ullam veniam. Est modi exercitationem quos fugiat voluptas obcaecati esse dolores, eos voluptatibus tempore quasi iste laborum deserunt nesciunt delectus laudantium eligendi nemo culpa, asperiores sed, maxime vero? Laboriosam fugiat quis minima quo dolores eaque maxime, blanditiis ut inventore autem ea ducimus quasi sapiente at odit ab tenetur! Magnam odio debitis maiores ex, quibusdam repellendus voluptates tenetur eum blanditiis dolore doloribus alias accusamus sapiente quasi harum incidunt, cumque excepturi. Omnis quae error delectus incidunt veniam quidem aspernatur nam voluptatem natus tempore voluptates quod corporis debitis dolorum esse in, sunt saepe earum alias. Minima mollitia nemo quia debitis eius? Adipisci, at beatae! Ipsa ut, sint voluptatem repudiandae voluptate in debitis, voluptas nostrum id tempore vitae asperiores dignissimos! Ad aperiam dolorum ducimus repudiandae rerum ipsam optio corporis culpa sunt id quas reiciendis in alias earum cumque veritatis iste eveniet nesciunt assumenda quae, consequatur itaque qui. Perspiciatis, repellendus cum quasi laboriosam blanditiis necessitatibus. Dolores rem hic quas voluptatibus, cum tempora voluptates at earum ipsum ea laboriosam ut sed provident asperiores architecto assumenda corrupti? Iure delectus magni amet qui illo unde necessitatibus iusto quia doloribus iste consequatur corporis totam sequi repudiandae dolorem repellendus maiores architecto consectetur, earum quisquam! Accusantium sit, eligendi hic, dolorem numquam provident sed rem earum illo molestiae assumenda alias dicta tempore quo ullam ipsam fuga pariatur optio beatae.</p>
           <Footer/>
        </div>
    );
};

export default Lodging;